spring:
  application:
    name: bank-account-service
  datasource:
    url: jdbc:postgresql://localhost:5433/testapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
    enabled: true
    schemas: public
