app:
  name: "@project.name@"
  apiVersion: "@bank-account-service.version@"
  description: "@project.description@"
  balance-checker:
    fixed-rate: 30000

spring:
  application:
    name: bank-account-service
  datasource:
    url: jdbc:postgresql://localhost:5433/testapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  flyway:
    baselineOnMigrate: true
    locations: classpath:db/migration
    enabled: true
    schemas: public
  data:
    redis:
      host: localhost
      port: 6379
      password: redis

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 36000000